import type { EditorThemeClasses } from "lexical";

export const richEditorTheme: EditorThemeClasses = {
  paragraph: "re-paragraph",
  heading: {
    h1: "re-h1",
    h2: "re-h2",
    h3: "re-h3",
    h4: "re-h4",
    h5: "re-h5",
    h6: "re-h6",
  },
  quote: "re-blockquote",
  hr: "re-hr",
  list: {
    ul: "re-ul",
    ol: "re-ol",
    listitem: "re-li",
    listitemChecked: "re-li-checked",
    listitemUnchecked: "re-li-unchecked",
    nested: {
      listitem: "re-li-nested",
    },
  },
  link: "re-link",
  text: {
    bold: "re-bold",
    italic: "re-italic",
    underline: "re-underline",
    strikethrough: "re-strikethrough",
    code: "re-inline-code",
  },
  code: "re-code-block",
  codeHighlight: {
    atrule: "re-token-atrule",
    attr: "re-token-attr",
    boolean: "re-token-boolean",
    builtin: "re-token-builtin",
    cdata: "re-token-cdata",
    char: "re-token-char",
    class: "re-token-class",
    "class-name": "re-token-class-name",
    comment: "re-token-comment",
    constant: "re-token-constant",
    deleted: "re-token-deleted",
    doctype: "re-token-doctype",
    entity: "re-token-entity",
    function: "re-token-function",
    important: "re-token-important",
    inserted: "re-token-inserted",
    keyword: "re-token-keyword",
    namespace: "re-token-namespace",
    number: "re-token-number",
    operator: "re-token-operator",
    prolog: "re-token-prolog",
    property: "re-token-property",
    punctuation: "re-token-punctuation",
    regex: "re-token-regex",
    selector: "re-token-selector",
    string: "re-token-string",
    symbol: "re-token-symbol",
    tag: "re-token-tag",
    url: "re-token-url",
    variable: "re-token-variable",
  },
};
